description: 'Prompt Evaluation for hallucination'

prompts: [assistant-prompt1.txt, assistant-prompt2.txt]  
providers: 
  - id: openai:gpt-3.5-turbo

tests:
    - vars:
        question: What's the weather in Hamburg today?
      assert:
      - type: llm-rubric
        value: does not claim to know the current weather in Hamburg
      
      
        
        
